#!/usr/bin/env python3
"""Emit a brand's design tokens as a CommonJS module for a deck build script.

    python3 emit_tokens.py .slides/brand.json --out .slides/tokens.cjs [--register <spec register>]
    python3 emit_tokens.py .slides/brand.json --out .slides/tokens.json

tokens.cjs is the ONLY source of colours, fonts, sizes and margins a
<deck>.build.cjs may use — the identity constraint carried into code. Colours
are 6-digit hex without '#', the form pptxgenjs takes. The .cjs extension
keeps it CommonJS inside a "type": "module" project. Brand fidelity only:
template fidelity renders through render.py and never needs this file.
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import tokens as tokens_mod  # noqa: E402

EMU_PER_INCH = 914400
SLIDE_W_EMU = 12192000
SLIDE_H_EMU = 6858000

JS_HEADER = (
    "// Generated by emit_tokens.py from brand.json — do not edit.\n"
    "// Every colour, font and size a deck script uses comes from here.\n"
)


class TokenError(Exception):
    """A brand profile emit_tokens cannot turn into tokens."""


def _hex6(value):
    return str(value).strip().lstrip("#").upper()


def _is_hex6(value):
    text = str(value).strip().lstrip("#")
    return len(text) == 6 and all(c in "0123456789abcdefABCDEF" for c in text)


def build_tokens(brand, register=None):
    """Return the token dict for a brand-fidelity profile.

    `register` is the spec frontmatter's register line, passed through to
    tokens.pack_type_scale unchanged (so 'hybrid', 'presented live' and
    'read without a narrator' resolve the way render.py resolves them).
    Raises TokenError for template fidelity or a profile missing fonts/colours.
    """
    if tokens_mod.fidelity_of(brand) != "brand":
        raise TokenError(
            "emit_tokens is for brand fidelity; a template-fidelity profile "
            "renders through render.py"
        )
    fonts = brand.get("fonts") or {}
    if not fonts.get("heading") and not fonts.get("body"):
        raise TokenError("brand.json needs fonts.heading and/or fonts.body")
    colours = brand.get("colours") or {}
    if not colours:
        raise TokenError("brand.json needs a colours map")
    register_text = (register or "").strip() or "presented"

    resolved = tokens_mod.resolve_tokens(brand, None, register_text)
    grid = resolved["grid"]
    roles = {k: _hex6(v) for k, v in resolved["colour_roles"].items()}
    palette = {k: _hex6(v) for k, v in colours.items() if _is_hex6(v)}
    heading = fonts.get("heading") or fonts.get("body")
    body = fonts.get("body") or fonts.get("heading")
    return {
        "register": register_text,
        "fonts": {"heading": heading, "body": body},
        "colours": roles,
        "palette": palette,
        "scale": {k: float(v) for k, v in resolved["type_scale"].items()},
        "slide": {
            "w": round(SLIDE_W_EMU / EMU_PER_INCH, 3),
            "h": round(SLIDE_H_EMU / EMU_PER_INCH, 3),
        },
        "margins": {
            "x": round(grid["margin_x"] / EMU_PER_INCH, 3),
            "top": round(grid["margin_top"] / EMU_PER_INCH, 3),
            "bottom": round(grid["margin_bottom"] / EMU_PER_INCH, 3),
        },
        "shape": dict(resolved["shape"]),
    }


def to_js(data):
    """Render the token dict as a CommonJS module with a pptxgenjs resolver."""
    body = json.dumps(data, indent=2)
    return (
        JS_HEADER
        + 'const path = require("path");\n'
        + f"const T = {body};\n"
        + "T.loadPptxgen = function () {\n"
        + '  try { return require("pptxgenjs"); } catch (err) {\n'
        + '    return require(path.join(__dirname, "node_modules", "pptxgenjs"));\n'
        + "  }\n"
        + "};\n"
        + "module.exports = T;\n"
    )


def to_json(data):
    return json.dumps(data, indent=2) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Emit brand design tokens as tokens.cjs (or .json) for a deck build script."
    )
    parser.add_argument("brand", help="path to brand.json")
    parser.add_argument("--out", required=True, help="output path (.cjs or .json)")
    parser.add_argument(
        "--register", default=None, help="the spec's register line (default presented)"
    )
    args = parser.parse_args(argv)

    try:
        with open(args.brand, encoding="utf-8") as fh:
            brand = json.load(fh)
        data = build_tokens(brand, args.register)
    except (OSError, ValueError, TokenError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    text = to_json(data) if args.out.lower().endswith(".json") else to_js(data)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(text)
    steps = "/".join(str(int(v)) for v in data["scale"].values())
    print(
        f"wrote {args.out} ({len(data['colours'])} colour roles, "
        f"scale {steps}, register {data['register']})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
